require_relative './app/book'
require_relative './app/author'
require_relative './app/label'
require_relative './app/music_album'
require_relative './app/genre'
require_relative './app/movie'
require_relative './app/game'
require_relative './app/source'

# import the logic files
require_relative './logic/book_logic'
require_relative './logic/author_logic'
require_relative './logic/game_logic'
require_relative './logic/label_logic'
require_relative './logic/source_logic'
require_relative './logic/movies_logic'
require_relative './logic/music_album_logic'
require_relative './logic/genre_logic'
